import { GraduationCap, ShieldCheck } from "lucide-react";
import { auth, signIn } from "@/lib/auth";
import { redirect } from "next/navigation";

export default async function LoginPage() {
  const session = await auth();
  if (session) redirect(session.user.role === "ADMIN" ? "/admin/dashboard" : "/dashboard");
  return <main className="login-page"><section className="login-story"><div className="login-brand"><GraduationCap /><span>IIIT Lucknow</span></div><div><span className="eyebrow">Training & Placement Cell</span><h1>Your career journey,<br />all in one place.</h1><p>Discover opportunities, manage applications, and stay connected with the placement cell.</p></div><small>Indian Institute of Information Technology Lucknow</small></section><section className="login-panel"><div className="login-card"><div className="login-icon"><ShieldCheck /></div><span className="eyebrow">Student portal</span><h2>Welcome back</h2><p>Sign in using your official institute Google account.</p><form action={async () => { "use server"; await signIn("google", { redirectTo: "/dashboard" }); }}><button type="submit"><span className="google-g">G</span>Continue with Google</button></form><div className="login-divider"><span>or use local testing</span></div><form className="test-login" action={async (formData) => { "use server"; await signIn("credentials", { email: formData.get("email"), password: formData.get("password"), redirectTo: "/dashboard" }); }}><label>Email<input name="email" type="email" defaultValue="student@iiitl.ac.in" required /></label><label>Password<input name="password" type="password" defaultValue="student123" required /></label><button className="test-button" type="submit">Sign in with test credentials</button></form><div className="login-note">Student: <strong>student@iiitl.ac.in</strong> / <strong>student123</strong><br />Admin: <strong>admin@iiitl.ac.in</strong> / <strong>admin123</strong><br />Disabled automatically in production.</div></div></section></main>;
}
