import { notFound } from "next/navigation";
import { ArrowLeft, BriefcaseBusiness, CalendarDays, CheckCircle2, IndianRupee, MapPin, XCircle } from "lucide-react";
import Link from "next/link";
import { ApplyButton } from "@/components/jobs/apply-button";
import { PortalShell } from "@/components/layout/portal-shell";
import { jobProfiles } from "@/lib/mock-data";

export function generateStaticParams(){return jobProfiles.map(job=>({id:job.id}))}
export default async function Page({params}:{params:Promise<{id:string}>}){const{id}=await params;const job=jobProfiles.find(item=>item.id===id);if(!job)notFound();const checks=[{label:`CGPA 8.2 ≥ ${job.minCgpa}`,pass:8.2>=job.minCgpa},{label:"Batch 2027",pass:job.batch===2027},{label:"Branch CSE",pass:job.branches.includes("CSE")},{label:`Backlogs 0 ≤ ${job.maxBacklogs}`,pass:0<=job.maxBacklogs},{label:"Profile documents complete",pass:true}];const eligible=checks.every(c=>c.pass)&&job.status==="Active";return <PortalShell><div className="job-detail"><Link className="back-link" href="/company-events"><ArrowLeft/>Back to opportunities</Link><div className="job-detail-grid"><article className="job-main"><div className="job-hero"><div className="detail-logo" style={{background:job.color}}>{job.initials}</div><div><span>{job.company}</span><h1>{job.title}</h1><b>{job.type}</b></div></div><div className="job-facts"><div><MapPin/><span>Location<strong>{job.location}</strong></span></div><div><IndianRupee/><span>Compensation<strong>{job.stipend}</strong></span></div><div><CalendarDays/><span>Deadline<strong>{job.deadline}</strong></span></div><div><BriefcaseBusiness/><span>Batch<strong>{job.batch}</strong></span></div></div><section><h2>Opening overview</h2><p>{job.description}</p></section><section><h2>Eligibility criteria</h2><dl><div><dt>Minimum CGPA</dt><dd>{job.minCgpa}</dd></div><div><dt>Maximum backlogs</dt><dd>{job.maxBacklogs}</dd></div><div><dt>Allowed branches</dt><dd>{job.branches.join(", ")}</dd></div></dl></section></article><aside className="eligibility-card"><span className="eyebrow">Automatic evaluation</span><h2>{eligible?"You are eligible":"Not currently eligible"}</h2><p>Based on your test student profile.</p><div>{checks.map(check=><span className={check.pass?"pass":"fail"} key={check.label}>{check.pass?<CheckCircle2/>:<XCircle/>}{check.label}</span>)}</div><ApplyButton disabled={!eligible}/><small>Submitting uses your default resume. This test interaction does not persist until the database is connected.</small></aside></div></div></PortalShell>}
