export const jobProfiles = [
  { id:"atlassian-swe", company:"Atlassian", initials:"AT", color:"#1868db", title:"Software Engineer Intern", type:"Internship + PPO", location:"Bengaluru", deadline:"13 Jul 2026, 6:00 PM", status:"Active", stipend:"₹1,20,000 / month", batch:2027, minCgpa:7.5, maxBacklogs:0, branches:["CSE","CSAI","IT"], description:"Join the engineering team building collaboration products used by millions of people. Interns own a scoped project, work with a mentor, and participate in design and code reviews." },
  { id:"google-summer", company:"Google", initials:"G", color:"#4285f4", title:"Summer Internship 2027", type:"Internship", location:"Bengaluru / Hyderabad", deadline:"18 Jul 2026, 11:59 PM", status:"Active", stipend:"Competitive", batch:2027, minCgpa:7, maxBacklogs:0, branches:["CSE","CSAI","IT","ECE"], description:"Work on a technical project with Google engineers while developing software engineering skills in a collaborative environment." },
  { id:"adobe-mts", company:"Adobe", initials:"A", color:"#e11d48", title:"Member of Technical Staff", type:"FTE", location:"Noida / Bengaluru", deadline:"20 Jul 2026, 5:00 PM", status:"Active", stipend:"₹32 LPA", batch:2027, minCgpa:8, maxBacklogs:0, branches:["CSE","CSAI","IT"], description:"Build creative and document experiences at scale as a member of Adobe's graduate engineering program." },
  { id:"phonepe-sde", company:"PhonePe", initials:"P", color:"#6739b7", title:"Software Development Engineer", type:"FTE", location:"Bengaluru", deadline:"08 Jul 2026, 3:00 PM", status:"Closed", stipend:"₹28 LPA", batch:2027, minCgpa:7.5, maxBacklogs:0, branches:["CSE","CSAI","IT"], description:"Develop reliable payment systems and consumer experiences for one of India's largest fintech platforms." },
  { id:"goldman-analyst", company:"Goldman Sachs", initials:"GS", color:"#7399c6", title:"Summer Analyst", type:"Internship + PPO", location:"Bengaluru / Hyderabad", deadline:"25 Jul 2026, 6:00 PM", status:"Active", stipend:"₹1,00,000 / month", batch:2027, minCgpa:7, maxBacklogs:1, branches:["CSE","CSAI","IT","ECE"], description:"Solve business and engineering challenges across financial platforms, risk, and data systems." }
] as const;

export type JobProfile = (typeof jobProfiles)[number];
